//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYS_Web.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BYSDNEntities : DbContext
    {
        public BYSDNEntities()
            : base("name=BYSDNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Answer> Table_Answer { get; set; }
        public virtual DbSet<Table_Attachments> Table_Attachments { get; set; }
        public virtual DbSet<Table_LogEntity> Table_LogEntity { get; set; }
        public virtual DbSet<Table_OperationLog> Table_OperationLog { get; set; }
        public virtual DbSet<Table_OperationType> Table_OperationType { get; set; }
        public virtual DbSet<Table_Question> Table_Question { get; set; }
        public virtual DbSet<Table_User> Table_User { get; set; }
        public virtual DbSet<Table_Blog> Table_Blog { get; set; }
        public virtual DbSet<Table_BlogItem> Table_BlogItem { get; set; }
        public virtual DbSet<Table_BlogAttachments> Table_BlogAttachments { get; set; }
    }
}
