//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYS_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Blog
    {
        public Table_Blog()
        {
            this.Table_BlogAttachments = new HashSet<Table_BlogAttachments>();
            this.Table_BlogReply = new HashSet<Table_BlogReply>();
        }
    
        public System.Guid ID { get; set; }
        public int Status { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid Publisher { get; set; }
        public System.Guid BlogItemId { get; set; }
        public string Title { get; set; }
    
        public virtual Table_BlogItem Table_BlogItem { get; set; }
        public virtual Table_User Table_User { get; set; }
        public virtual ICollection<Table_BlogAttachments> Table_BlogAttachments { get; set; }
        public virtual ICollection<Table_BlogReply> Table_BlogReply { get; set; }
    }
}
