//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYS_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_LogEntity
    {
        public Table_LogEntity()
        {
            this.Table_OperationLog = new HashSet<Table_OperationLog>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid OperationTypeID { get; set; }
        public string LogType { get; set; }
        public string OriginValue { get; set; }
        public string NewValue { get; set; }
    
        public virtual Table_OperationType Table_OperationType { get; set; }
        public virtual ICollection<Table_OperationLog> Table_OperationLog { get; set; }
    }
}
