//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYS_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Question
    {
        public Table_Question()
        {
            this.Table_Answer = new HashSet<Table_Answer>();
            this.Table_Attachments = new HashSet<Table_Attachments>();
        }
    
        public System.Guid ID { get; set; }
        public string Tittle { get; set; }
        public string Tags { get; set; }
        public System.DateTime Date { get; set; }
        public string Content { get; set; }
        public System.Guid Publisher { get; set; }
    
        public virtual ICollection<Table_Answer> Table_Answer { get; set; }
        public virtual ICollection<Table_Attachments> Table_Attachments { get; set; }
        public virtual Table_User Table_User { get; set; }
    }
}
