//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYS_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_User
    {
        public Table_User()
        {
            this.Table_Answer = new HashSet<Table_Answer>();
            this.Table_OperationLog = new HashSet<Table_OperationLog>();
            this.Table_Question = new HashSet<Table_Question>();
            this.Table_Blog = new HashSet<Table_Blog>();
            this.Table_BlogReply = new HashSet<Table_BlogReply>();
            this.Table_SubBlogReply = new HashSet<Table_SubBlogReply>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public bool Sexy { get; set; }
        public System.DateTime Date { get; set; }
        public string Comments { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Rate { get; set; }
    
        public virtual ICollection<Table_Answer> Table_Answer { get; set; }
        public virtual ICollection<Table_OperationLog> Table_OperationLog { get; set; }
        public virtual ICollection<Table_Question> Table_Question { get; set; }
        public virtual ICollection<Table_Blog> Table_Blog { get; set; }
        public virtual ICollection<Table_BlogReply> Table_BlogReply { get; set; }
        public virtual ICollection<Table_SubBlogReply> Table_SubBlogReply { get; set; }
    }
}
