//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYS_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_LogEntity
    {
        public Table_LogEntity()
        {
            this.Table_OperationLog = new HashSet<Table_OperationLog>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid OperationTypeID { get; set; }
        public string LogType { get; set; }
        public string OriginValue { get; set; }
        public string NewValue { get; set; }
    
        public virtual Table_OperationType Table_OperationType { get; set; }
        public virtual ICollection<Table_OperationLog> Table_OperationLog { get; set; }
    }
}
