//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYS_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Answer
    {
        public System.Guid ID { get; set; }
        public System.Guid QuestionID { get; set; }
        public string Content { get; set; }
        public System.Guid Publisher { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Table_Question Table_Question { get; set; }
        public virtual Table_User Table_User { get; set; }
    }
}
