//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYS_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Blog
    {
        public Table_Blog()
        {
            this.Table_BlogAttachments = new HashSet<Table_BlogAttachments>();
        }
    
        public System.Guid ID { get; set; }
        public int Status { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid Publisher { get; set; }
        public System.Guid BlogItemId { get; set; }
        public string Title { get; set; }
    
        public virtual Table_BlogItem Table_BlogItem { get; set; }
        public virtual Table_User Table_User { get; set; }
        public virtual ICollection<Table_BlogAttachments> Table_BlogAttachments { get; set; }
    }
}
