//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYS_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_BlogAttachments
    {
        public System.Guid ID { get; set; }
        public System.Guid BlogID { get; set; }
        public string FileName { get; set; }
        public string FileSize { get; set; }
    
        public virtual Table_Blog Table_Blog { get; set; }
    }
}
